### ISSUE TITLE
Update PyPI Integration

### ISSUE THREAD

**Issue by rajadain** [azavea/django-ecsmanage#36]
With recent changes to PyPI trusted publishers, we need to update the CI to use that instead of the old non-functional username / password setup.

Update the integration so that releases may publish to PyPI again.

**Comment by JN-Hernandez** [comment]
# WorkPlan

## Summary

The `django-ecsmanage` Python packages is published via the Azavea PyPI account, however recent builds of these projects are failing because PyPI has changed from username/password authentication to token based and trusted-publisher based authentication.  This workplan is to document updating this integration.

## Steps

- [x] 1. Log in to TestPyPi using the `TestPyPi Python Package Index` credentials within **1Password**
- [x] 2. Click the `azavea` user in the top-right hand corner, then select `Your Projects` from the dropdown menu
- [x] 3. Traverse to `Publishing`, then scroll down to **Add a new publisher**
- [x] 4. Fill in the **Owner**, **Repository name**, and **Workflow name**, then click `Next`
> [!Note]
> Only use the actual repository name, not full GitHub URL nor the `azavea/` prefix.
- [x] 5. Log in to PyPI using the `Python Package Index (PyPi)` credentials within **1Password**
- [x] 6. Repeat steps 2-4 of this workplan to add a new publisher
- [x] 7. Update the `release.yml` GitHub Workflow to upload the release to TestPyPI
> [!Tip]
> Review commits https://github.com/azavea/django-ecsmanage/commit/879859d8d47e1f89cf4e76c674352a34306a9b6c and https://github.com/azavea/django-ecsmanage/commit/879859d8d47e1f89cf4e76c674352a34306a9b6c to see what changes in the file were made/needed.
- [x] 8. Update the `CHANGELOG.md` file to document the update
- [x] 9. Move through a manual release process and confirm upload works for TestPyPI
> [!Note]
> The manual release process involves making a new branch called `release/*` with the appropriate tags - once this is pushed upstream, this will trigger the release workflow
- [x] 10. Once approved, update the `release.yml` file to instead upload the release to PyPI
- [x] 11. Move through another manual release process to update the release
> [!Important]
> In order to kick off a new manual release, you will need to delete the tags from origin as well as locally.  Pushing up again will trigger another release workflow

## Criteria for Success

- [x] 1. Upload of the release to TestPyPI works as expected
- [x] 2. Upload of the release to PyPI works as expected

## Risk

Low Risk
1. Failure to implement this change will result in the release upload to PyPI not working

## Rollback

1. n/a - failure to implement this change will result in the release upload to PyPI not working

## Additional Details

- PyPI Integration Documentation: [Publishing to PyPI with a Trusted Publisher](https://docs.pypi.org/trusted-publishers/)
- GitHub Actions Documentation: [Triggering a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow)
- [How to Delete Local and Remote Tags on Git](https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/)
- Paired with @rajadain in order to understand and implement this integration update
